module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg)',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/.expo/**',
    '!**/coverage/**',
    '!**/jest.config.js',
    '!**/jest.setup.js',
    '!**/*.examples.ts',
    '!**/*.examples.tsx',
    '!**/index.ts',
    '!**/examples/**',
    '!**/shared/testing/**',
    '!**/shared/screens/**',
    '!**/shared/components/**',
    '!**/shared/hooks/**',
    '!**/shared/theme/**',
    '!**/shared/services/**',
    '!**/shared/i18n/**',
    '!**/shared/responsive.ts',
    '!**/features/**/presentation/**',
    '!**/features/**/domain/models/**',
    '!**/features/**/domain/entities/**',
    '!**/features/**/domain/repositories/**',
    '!**/features/**/domain/services/oauth.service.ts',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  testMatch: ['**/__tests__/**/*.(ts|tsx|js)', '**/*.(test|spec).(ts|tsx|js)'],
};
