export const SPLASH_SCREEN_CONFIG = {
  MINIMUM_DISPLAY_TIME: 2000,
  LOGO_ANIMATION_DURATION: 800,
  LOADER_ANIMATION_DURATION: 600,
  LOADER_ANIMATION_DELAY: 400,
  LOGO_INITIAL_SCALE: 0.8,
  LOGO_FINAL_SCALE: 1,
} as const;

export const SPLASH_SCREEN_COLORS = {
  BACKGROUND: '#FFFFFF',
  PRIMARY: '#007AFF',
  TEXT_PRIMARY: '#1A1A1A',
  TEXT_SECONDARY: '#666666',
} as const;

export const SPLASH_SCREEN_TEXTS = {
  APP_NAME: 'PillMind',
  TAGLINE: 'Sua saúde em suas mãos',
} as const;
